### ISSUE TITLE
copy/download crest on iOS

### ISSUE THREAD

**Issue by 0xKheops** [polkadot-builders-dao/polkadot-builders-dao#10]
Reported by Zooeys, the copy & download crest image feature isn't working on iOS

**Comment by replghost** [comment]
I believe there are two issues here:

1. OffScreen canvas is not supported in Safari until 16.4. This is currently available on mobile if you are fully updated, but not available in Safari desktop yet. Offscreen canvas is used to convert the svg to png. The error is  ```ReferenceError: Can't find variable: OffscreenCanvas``` [https://caniuse.com/offscreencanvas](https://caniuse.com/offscreencanvas)
2. Safari (mobile and desktop) have extra security around what is allowed to be copied, so even with 16.4, the copy still doesn't work, but with a different error: ```NotAllowedError...```.  - need to send a Promise to ClipboardItem - https://webkit.org/blog/10855/

**Comment by 0xKheops** [comment]
good catches !
